apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-lab
  labels:
    app: api-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-lab
  template:
    metadata:
      labels:
        app: api-lab
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: api
          image: python:3.12-slim
          command: ["sleep", "infinity"]
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
